### ISSUE TITLE
Przekaż stan początkowy przez props

### ISSUE THREAD

**Issue by devmentor-pl** [mlvrkhn/todo-react-practice#2]
https://github.com/mlvrkhn/todo-react-practice/blob/b7a89327498037b22d4bcf3aaefd3731a02a798c/src/App.js#L8-L23

Elastyczniej będzie jak przekażesz stan początkowy przez props do <ToDo> podczas uruchamiania w <App>

**Comment by mlvrkhn** [comment]
OK
