### ISSUE TITLE
Utwórz odpowiednią metodę

### ISSUE THREAD

**Issue by devmentor-pl** [mlvrkhn/todo-react-practice#3]
https://github.com/mlvrkhn/todo-react-practice/blob/b7a89327498037b22d4bcf3aaefd3731a02a798c/src/App.js#L38

Kod nie jest super czytelny, lepiej zasugerować co on robi przez stworzenie odpowiedniej funkcji i jej wywołanie np. getNextNumber()

**Comment by mlvrkhn** [comment]
fixed
