### ISSUE TITLE
Utwórz metody pomocnicze

### ISSUE THREAD

**Issue by devmentor-pl** [mlvrkhn/todo-react-practice#4]
https://github.com/mlvrkhn/todo-react-practice/blob/b7a89327498037b22d4bcf3aaefd3731a02a798c/src/App.js#L35-L43

Proponuję utworzyć osobne funkcje, które będę okreslać co robisz np. `createTask(taksName)`, `clearForm()`

**Comment by mlvrkhn** [comment]
OK poprawione.
